### ISSUE TITLE
关于数据集的问题

### ISSUE THREAD

**Issue by ImmortalFish** [vonfeng/DPLink#2]
您好，我按照Readme中提到的向Dr. Yong li 发邮件请求数据集，但是可能教授过于繁忙，至今未收到回复，请问您能提供一份**ISP-Weibo**的数据集给我吗？我的邮箱是tenglei.cq@gmail.com

**Comment by vonfeng** [comment]
不好意思，回复的有些晚了。如果这边还需要该数据集进行学术研究，可以重新发送邮件给我，我会代为转发和提醒

**Comment by Hunanglirong** [comment]
您好，我之前也给Dr. Yong li 发邮件请求数据集，但是可能由于教授过于繁忙，至今未收到回复，能否帮我询问一下李教授？我的邮箱是huanglr@mail.nwpu.edu.cn

**Comment by vonfeng** [comment]
[ISP-Weibo](https://github.com/vonfeng/DPLink/tree/master/data) data has been open-sourced and is available for use.
